name: Build Docker Image then push to GitHub Packages

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      WORKING_DIR:
        required: true
        type: string
    outputs:
      timestamp:
        description: 'Build timestamp'
        value: ${{ jobs.build-image-push.outputs.timestamp }}    
    secrets:
      GHCR_PAT:
        required: true

jobs:
  build-image-push:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-timestamp.outputs.timestamp }}

    env:
      BRANCH_NAME: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call composite action to extract branch name
        id: extract-branch-name
        uses: david-gimelle/lab/.github/actions/extract-branch-name@main

      - name: Set branch name from composite action
        run: echo "BRANCH_NAME=${{ steps.extract-branch-name.outputs.branch_name }}" >> $GITHUB_ENV

      - name: Set timestamp
        id: set-timestamp
        run: |
          echo "TIMESTAMP=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          echo "timestamp=${{ env.TIMESTAMP }}" >> $GITHUB_OUTPUT
    
      - name: Display timestamp
        run: echo "Build timestamp is ${{ steps.set-timestamp.outputs.timestamp }}"
       
      - name: Display branch name from composite action
        run: echo "Branch name is ${{ env.BRANCH_NAME }}"

      - name: Display APP_NAME and WORKING_DIR
        run: |
          echo "APP_NAME: ${{ inputs.APP_NAME }}"
          echo "WORKING_DIR: ${{ inputs.WORKING_DIR }}"

      - name: Log in to GitHub Docker registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ env.TIMESTAMP }} .
        working-directory: ./${{ inputs.WORKING_DIR }}

      - name: Tag Docker image
        run: |
          docker tag ${{ inputs.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ env.TIMESTAMP }} ghcr.io/${{ github.repository }}/${{ inputs.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ env.TIMESTAMP }}

      - name: Cleanup dangling images
        run: docker image prune -f

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ inputs.APP_NAME }}:${{ env.BRANCH_NAME }}-${{ env.TIMESTAMP }}
